# Generated by Django 4.2.30 on 2026-08-03 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_color_course_description_course_icon_and_more'),
        ('tests_app', '0003_test_free_preview_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], default='percentage', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('applies_to', models.CharField(choices=[('all', 'Entire store'), ('qbank', 'Question Bank Subscription'), ('daily_test', 'Daily Test Subscription'), ('mock_test', 'Mock Test Package'), ('grand_test', 'Grand Test')], default='all', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited total redemptions.', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('first_purchase_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test')], max_length=20)),
                ('name', models.CharField(help_text='e.g. "3 Month QBank Access", "30 Mock Tests / 3 Months"', max_length=150)),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('day', 'Day(s)'), ('week', 'Week(s)'), ('month', 'Month(s)'), ('year', 'Year(s)')], default='month', max_length=10)),
                ('mock_test_quota', models.PositiveIntegerField(blank=True, help_text='Only for Mock Test plans — how many mock tests this package includes. Blank = unlimited.', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'product_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test')], max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('mock_test_quota', models.PositiveIntegerField(blank=True, null=True)),
                ('mock_test_used', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.course')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('subscription', 'Subscription'), ('grand_test', 'Grand Test')], max_length=15)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transfer / eSewa / Khalti reference number the student provides as proof of payment.', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='billing.coupon')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grand_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='tests_app.test')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='billing.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrandTestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=20, unique=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grand_test_access', to='billing.purchase')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accesses', to='tests_app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_test_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
    ]
