# Generated by Django 4.2.30 on 2026-08-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_legacy_exam_models'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='Automatically applied (best-value one wins) when the student has not typed a code.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Blank = applies across every course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='eligibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('registered', 'Registered Users Only'), ('first_purchase', 'First Purchase Only'), ('new_students', 'New Students'), ('specific_emails', 'Specific Email Addresses')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='eligible_emails',
            field=models.TextField(blank=True, help_text='Comma-separated emails — only used when eligibility="Specific Email Addresses".'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='new_student_days',
            field=models.PositiveIntegerField(default=30, help_text='Only used when eligibility="New Students" — days since registration to still count as new.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage'), ('free_exam', 'Free Exam'), ('free_subscription', 'Free Subscription'), ('free_grand_test', 'Free Grand Test')], default='percentage', max_length=20),
        ),
    ]
