# Generated by Django 4.2.30 on 2026-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_promo_upgrade_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applies_to',
            field=models.CharField(choices=[('all', 'Entire store'), ('qbank', 'Question Bank Subscription'), ('daily_test', 'Daily Test Subscription'), ('mock_test', 'Mock Test Package'), ('grand_test', 'Grand Test'), ('video', 'Video Lectures Subscription')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product_type',
            field=models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test'), ('video', 'Video Lectures')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product_type',
            field=models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test'), ('video', 'Video Lectures')], max_length=20),
        ),
    ]
