# Generated by Django 4.2.30 on 2026-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_scholarship_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'Fonepay'), ('connectips', 'ConnectIPS')], help_text='Which channel the student says they paid through — still manually verified, no live gateway.', max_length=15),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_best_value',
            field=models.BooleanField(default=False, help_text='Shows a "Best Value" badge on the plan card.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Shows a "Popular" badge on the plan card.'),
        ),
    ]
