# Generated by Django 4.2.30 on 2026-08-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_vestigial_promo_code'),
        ('billing', '0008_purchase_status_and_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Blank = applies across every course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='courses.course'),
        ),
    ]
