# Generated by Django 4.2.30 on 2026-08-21 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
        ('billing', '0009_alter_coupon_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='billing.purchase'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_info',
            field=models.TextField(blank=True, help_text='Bank/account number or other identifying info shown alongside the QR, if needed.'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='merchant_id',
            field=models.CharField(blank=True, help_text='Merchant/account ID for this channel, if applicable.', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='merchant_name',
            field=models.CharField(blank=True, help_text="The merchant/account holder's name shown on the QR receipt.", max_length=150),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='provider_type',
            field=models.CharField(choices=[('fonepay', 'Fonepay'), ('khalti', 'Khalti'), ('esewa', 'eSewa'), ('connectips', 'connectIPS'), ('bank_qr', 'Bank QR'), ('other', 'Other')], default='other', help_text='Which QR/payment network this is — drives future automatic-verification routing (see billing.payment_providers). Purely informational today.', max_length=15),
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='NRS', help_text='NRS only — this platform does not support other currencies.', max_length=3),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='QR payment window deadline (created_at + 30 min) for orders with a nonzero amount. Null for free/100%-off orders, which never expire since nothing is owed.', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_screenshot_bucket',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_screenshot_key',
            field=models.CharField(blank=True, help_text='GCS object key (private bucket) for the submitted screenshot.', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='teacher_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='marketplace.teachercourse'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('reminder_30', '30 days before expiry'), ('reminder_15', '15 days before expiry'), ('reminder_7', '7 days before expiry'), ('reminder_3', '3 days before expiry'), ('reminder_1', '1 day before expiry'), ('expiry', 'On expiry'), ('grace_period', 'Grace period'), ('renewal_confirmation', 'Renewal confirmation'), ('payment_submitted', 'Payment submitted'), ('payment_approved', 'Payment approved'), ('payment_rejected', 'Payment rejected'), ('payment_expired', 'Payment expired')], max_length=25),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('grand_test', 'Grand Test'), ('teacher_course', 'Teacher Course')], max_length=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Bank transfer / eSewa / Khalti reference number the student provides as proof of payment.', max_length=150),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('resubmission_requested', 'Resubmission Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='unpaid', max_length=25),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='product_type',
            field=models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test'), ('video', 'Video Lectures'), ('pyq', 'Past Year Questions')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product_type',
            field=models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test'), ('video', 'Video Lectures'), ('pyq', 'Past Year Questions')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product_type',
            field=models.CharField(choices=[('qbank', 'Practice Question Bank'), ('daily_test', 'Daily Test'), ('mock_test', 'Mock Test'), ('video', 'Video Lectures'), ('pyq', 'Past Year Questions')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Payment submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission requested'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=25)),
                ('previous_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra structured context, e.g. {"payment_reference": "..."}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='billing.purchase')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase', 'created_at'], name='billing_pay_purchas_16ae7e_idx')],
            },
        ),
    ]
