# Generated by Django 4.2.30 on 2026-08-23 16:24, reordered by hand so the
# old single `course` FK is copied into the new `courses` M2M before it's
# dropped — a plain add-then-remove (Django's default operation order) would
# silently lose every existing coupon's course scoping.

from django.db import migrations, models


def copy_course_into_courses(apps, schema_editor):
    Coupon = apps.get_model('billing', 'Coupon')
    for coupon in Coupon.objects.filter(course__isnull=False):
        coupon.courses.add(coupon.course_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_vestigial_promo_code'),
        ('billing', '0010_notificationlog_purchase_paymentmethod_account_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Blank = applies across every course.', related_name='coupons', to='courses.course'),
        ),
        migrations.RunPython(copy_course_into_courses, noop_reverse),
        migrations.RemoveField(
            model_name='coupon',
            name='course',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applies_to',
            field=models.CharField(choices=[('all', 'Entire store'), ('qbank', 'Question Bank Subscription'), ('daily_test', 'Daily Test Subscription'), ('mock_test', 'Mock Test Package'), ('grand_test', 'Grand Test'), ('video', 'Video Lectures Subscription'), ('pyq', 'Past Year Questions Subscription')], default='all', max_length=20),
        ),
    ]
