# Generated by Django 4.2.30 on 2026-08-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_vestigial_promo_code'),
        ('billing', '0011_remove_coupon_course_coupon_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('grand_test', 'Grand Test'), ('teacher_course', 'Teacher Course'), ('combo', 'Combo Plan')], max_length=15),
        ),
        migrations.CreateModel(
            name='PurchaseComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_purchase_items', to='billing.subscriptionplan')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='billing.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='ComboPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Ultimate Medical Prep"', max_length=150)),
                ('discount_percent', models.PositiveIntegerField(default=15, help_text='Percent off the combined individual price. Capped at 35%.')),
                ('is_popular', models.BooleanField(default=False, help_text='Shows a "Popular" badge on the combo card.')),
                ('is_best_value', models.BooleanField(default=False, help_text='Shows a "Best Value" badge on the combo card.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_plans', to='courses.course')),
                ('plans', models.ManyToManyField(help_text='Exact plan rows included in this combo (pick specific durations/quotas).', related_name='combo_plans', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='combo_plan',
            field=models.ForeignKey(blank=True, help_text='Set for a predefined-bundle purchase, null for a custom "build your own" combo — either way the actual items are PurchaseComboItem rows, not this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='billing.comboplan'),
        ),
    ]
