# Generated by Django 4.2.30 on 2026-09-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
        ('billing', '0012_alter_purchase_kind_purchasecomboitem_comboplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandtestaccess',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Payment submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission requested'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=25),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('resubmission_requested', 'Resubmission Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='unpaid', max_length=25),
        ),
        migrations.CreateModel(
            name='PurchaseEntitlementGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_created', models.BooleanField(default=True, help_text='True = this purchase created the access record (refund deactivates it). False = it extended an existing one (refund restores previous_expires_at instead).')),
                ('previous_expires_at', models.DateTimeField(blank=True, help_text="The access record's expiry BEFORE this purchase touched it — what a refund restores. Null when was_created (there was nothing before) or for a lifetime grant.", null=True)),
                ('granted_expires_at', models.DateTimeField(blank=True, help_text='What the expiry became after this purchase. Informational/auditing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Set when a refund reversed this grant. Non-null = already reversed, so a repeated refund is a safe no-op (idempotency marker).', null=True)),
                ('course_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_grants', to='marketplace.courseenrollment')),
                ('grand_test_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_grants', to='billing.grandtestaccess')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_grants', to='billing.purchase')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_grants', to='billing.subscription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
