# Generated by Django 4.2.30 on 2026-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_phase9_refund_and_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Bullet points shown on the plan card, e.g. ["All subjects", "Detailed solutions"]. Leave empty to show a line generated from this plan\'s own duration/quota.'),
        ),
    ]
