# Generated by Django 4.2.30 on 2026-09-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0025_test_review_duration_days'),
        ('billing', '0014_phase10_plan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('grand_test', 'Grand Test'), ('teacher_course', 'Teacher Course'), ('combo', 'Combo Plan'), ('grand_test_package', 'Grand Test Package')], max_length=20),
        ),
        migrations.CreateModel(
            name='GrandTestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Grand Test 5-Pack"', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Flat bulk price, e.g. Rs. 100 for a 5-pack.', max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tests', models.ManyToManyField(help_text="The exact Grand Tests currently included (exam_type='grand'). Editable — see this model's own docstring for why an edit here never retroactively changes an already-purchased entitlement.", related_name='grand_test_packages', to='tests_app.test')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='grand_test_package',
            field=models.ForeignKey(blank=True, help_text='GT3-5: which predefined package this purchase bought (for billing-history display, e.g. "Grand Test 5-Pack — Rs. 100") — mirrors combo_plan above exactly. The actual entitled Grand Tests are PurchaseGrandTestPackageItem rows, not this field, for the same reason combo_plan is not where PurchaseComboItem content lives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='billing.grandtestpackage'),
        ),
        migrations.CreateModel(
            name='PurchaseGrandTestPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_test_package_items', to='billing.purchase')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchase_items', to='tests_app.test')),
            ],
            options={
                'unique_together': {('purchase', 'test')},
            },
        ),
    ]
