# Generated by Django 4.2.30 on 2026-09-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_purchase_kind_grandtestpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandtestaccess',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grand_test_access', to='billing.purchase'),
        ),
    ]
