steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/hamromentor-app/hamromentor-repo/backend:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/hamromentor-app/hamromentor-repo/backend:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - hamromentor-backend
      - --image=asia-south1-docker.pkg.dev/hamromentor-app/hamromentor-repo/backend:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=hamromentor-app:us-central1:hamromentor-db-uc1
      - --set-env-vars=DB_NAME=hamromentor,DB_USER=hamromentor_app,DB_HOST=/cloudsql/hamromentor-app:us-central1:hamromentor-db-uc1,DJANGO_DEBUG=False,GCP_PROJECT_ID=hamromentor-app,GCP_REGION=us-central1,MEDIA_GCS_PRIVATE_BUCKET=hamromentor-media-private,MEDIA_GCS_PUBLIC_BUCKET=hamromentor-media-public,CLOUD_TASKS_QUEUE=image-processing,BACKEND_INTERNAL_URL=https://api.drgutka.com,IMAGE_PROCESSING_ASYNC=True
      - --set-secrets=DB_PASSWORD=db-password:latest,DJANGO_SECRET_KEY=django-secret-key:latest,MEDIA_PROCESSING_SECRET=media-processing-secret:latest,CRON_SECRET=cron-secret:latest
images:
  - 'asia-south1-docker.pkg.dev/hamromentor-app/hamromentor-repo/backend:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
