# Generated by Django 4.2.30 on 2026-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(default='📘', max_length=10)),
                ('color', models.CharField(default='#0b5fd9', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.CharField(default='/register', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=4)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('nav', 'Navbar'), ('footer', 'Footer')], max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_badge_text', models.CharField(default='📱 App coming soon', max_length=100)),
                ('nav_cta_text', models.CharField(default='Login/Signup', max_length=50)),
                ('hero_headline', models.CharField(default='The Trusted Path to NEET-PG & NMCLE Success', max_length=255)),
                ('hero_subtitle', models.TextField(default='QBank, mock tests and video lectures for CEE-UG, CEE-PG and NMCLE aspirants — built for how the real exam works.')),
                ('hero_cta_primary_text', models.CharField(default='Get Started', max_length=50)),
                ('hero_cta_primary_link', models.CharField(default='/register', max_length=255)),
                ('hero_cta_secondary_text', models.CharField(default='View Courses ›', max_length=50)),
                ('hero_cta_secondary_link', models.CharField(default='#courses', max_length=255)),
                ('hero_badge_icon', models.CharField(default='🔥', max_length=10)),
                ('hero_badge_title', models.CharField(default='MCQ of the Day', max_length=100)),
                ('hero_badge_tag', models.CharField(default='LIVE', max_length=30)),
                ('hero_badge_subtitle', models.CharField(default='A fresh high-yield MCQ, every day', max_length=150)),
                ('hero_badge_cta_text', models.CharField(default='Check it out ›', max_length=50)),
                ('hero_badge_link', models.CharField(default='/login', max_length=255)),
                ('stats_icon', models.CharField(default='📝', max_length=10)),
                ('stats_headline', models.CharField(default="A growing Test Series built for Nepal's medical aspirants", max_length=255)),
                ('stats_headline_highlight', models.CharField(blank=True, default='Test Series', help_text='Substring of the headline above to highlight in brand blue.', max_length=100)),
                ('stats_body', models.TextField(default='Grand, Mini and Subject tests with negative marking, shuffled questions and instant subject-wise scoring — practice under exam conditions before the real thing, and see exactly where you stand.')),
                ('stats_cta_text', models.CharField(default='Get started ›', max_length=50)),
                ('stats_cta_link', models.CharField(default='/register', max_length=255)),
                ('stats_image', models.ImageField(blank=True, help_text='Optional override for the phone-preview image (defaults to the built-in app screenshot).', null=True, upload_to='site/')),
                ('features_heading', models.CharField(default='What makes Hamromentor complete?', max_length=255)),
                ('features_heading_highlight', models.CharField(blank=True, default='Hamromentor', max_length=100)),
                ('courses_eyebrow', models.CharField(default='Pick your track', max_length=50)),
                ('courses_heading', models.CharField(default='Choose your course', max_length=100)),
                ('courses_subtitle', models.TextField(default='Every track comes with its own mock tests, question bank and video lectures. Pick yours and start practicing in minutes.')),
                ('footer_copyright', models.CharField(default='© 2026 Hamromentor. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
