# Generated by Django 4.2.30 on 2026-08-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursecard_homefeature_sitelink_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCard',
        ),
    ]
