# Generated by Django 4.2.30 on 2026-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_coursecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqoftheday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='features_heading',
            field=models.CharField(default='What makes Dr. Gutka complete?', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='features_heading_highlight',
            field=models.CharField(blank=True, default='Dr. Gutka', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2026 Dr. Gutka. All rights reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default='The Trusted Path to CEE-PG & NMCLE Success', max_length=255),
        ),
    ]
