# Generated by Django 4.2.30 on 2026-08-20 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_mcqoftheday_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('resource_type', models.CharField(help_text='e.g. "Question", "Course", "MediaAsset"', max_length=50)),
                ('resource_id', models.CharField(help_text='Stringified — some resources use UUID PKs, others int.', max_length=64)),
                ('resource_label', models.CharField(blank=True, help_text='Short human-readable identifier (e.g. a title or public_id) for audit-trail readability — never the full deleted content.', max_length=255)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='core_deleti_resourc_d9abcb_idx'), models.Index(fields=['created_at'], name='core_deleti_created_4c09d4_idx')],
            },
        ),
    ]
