# Generated by Django 4.2.30 on 2026-09-02 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_deletionauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEditAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('resource_type', models.CharField(help_text='e.g. "Student"', max_length=50)),
                ('resource_id', models.CharField(max_length=64)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('changed_fields', models.JSONField(default=dict, help_text='{"field_name": {"old": ..., "new": ...}, ...} — only fields that actually changed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='core_admine_resourc_874551_idx'), models.Index(fields=['created_at'], name='core_admine_created_467b70_idx')],
            },
        ),
    ]
