# Generated by Django 4.2.30 on 2026-08-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_color_course_description_course_icon_and_more'),
        ('accounts', '0002_rolepermission_user_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_course',
            field=models.ForeignKey(blank=True, help_text="The student's currently-selected subcourse — drives which QBank/Mock/Daily/Grand/PYQ content their dashboard shows.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course'),
        ),
    ]
