# Generated by Django 4.2.30 on 2026-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_all_content',
            field=models.BooleanField(default=False, help_text='Teacher-role only: if set, this account can see/manage every Test and Question, not just their own.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('teacher', 'Teacher')], max_length=20, null=True),
        ),
    ]
