# Generated by Django 4.2.30 on 2026-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_promo_upgrade_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_payment_channel',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], help_text='Pre-selected at checkout — informational only, this platform has no stored payment instrument.', max_length=10),
        ),
    ]
