# Generated by Django 4.2.30 on 2026-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_preferred_payment_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, help_text='Matches a courses.Course.prefix value the student registered under.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, help_text='e.g. CEE-PG, CEE-UG, NHPC — matches a Course.program_group value.', max_length=50),
        ),
    ]
