# Generated by Django 4.2.30 on 2026-08-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbs/')),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
                ('instructor_photo', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('is_free', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.subject')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
