# Generated by Django 4.2.30 on 2026-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='solutions_visibility',
            field=models.CharField(choices=[('auto', 'Automatically, once the exam window ends'), ('manual', 'Only when I click "Release solutions"')], default='auto', max_length=10),
        ),
    ]
