# Generated by Django 4.2.30 on 2026-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_test_solutions_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='free_preview_questions',
            field=models.PositiveIntegerField(default=0, help_text='For PRO Daily/Live tests only: how many questions a student without a subscription can preview. They can view but not submit those questions until they subscribe.'),
        ),
    ]
