# Generated by Django 4.2.30 on 2026-08-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_color_course_description_course_icon_and_more'),
        ('tests_app', '0003_test_free_preview_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Which subcourse(s) this exam is assigned to. Blank = visible to every enrolled student (unscoped).', related_name='mapped_tests', to='courses.course'),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, help_text='Short blurb shown on the exam card, e.g. "Sharpen your skills with exam-focused practice."'),
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.CharField(choices=[('grand', 'Grand Test'), ('mini', 'Mini Test'), ('subject', 'Subject Test'), ('daily', 'Daily Test'), ('live', 'Live Test'), ('pyq', 'Past Year Question')], default='mini', max_length=20),
        ),
    ]
