# Generated by Django 4.2.30 on 2026-08-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_add_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='On = only visible to staff (e.g. still being assembled via Import & Create Test). Off = visible to every eligible student, same as before this field existed.'),
        ),
    ]
