# Generated by Django 4.2.30 on 2026-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_test_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_per_page',
            field=models.PositiveIntegerField(default=1, help_text='How many questions show together on one exam page. 1 = one question per screen (classic).'),
        ),
    ]
