# Generated by Django 4.2.30 on 2026-08-09 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_vestigial_promo_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_app', '0008_test_questions_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='On = only visible to staff (e.g. still being assembled via Import & Create Test, or now managed through Exam Sessions). Off = visible to every eligible student, same as before this field existed.'),
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('qbank', 'Question Bank'), ('daily', 'Daily Test'), ('mock', 'Mock Test'), ('grand', 'Grand Test'), ('pyq', 'Past Year Questions')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('access_type', models.CharField(choices=[('all', 'All eligible students'), ('course', 'Specific course subscribers'), ('membership', 'Specific membership'), ('batch', 'Specific batch/group'), ('private', 'Private/password protected')], default='all', max_length=15)),
                ('password', models.CharField(blank=True, help_text="Used when access_type='private'.", max_length=50)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('registration_open', 'Registration Open'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('recurrence', models.CharField(choices=[('none', 'One time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_courses', models.ManyToManyField(blank=True, help_text="Used when access_type='course' — which course(s)' subscribers may take this session.", related_name='+', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests_app.examtemplate')),
                ('exam_version', models.ForeignKey(help_text='The Test row (question set + settings) this session uses. Never changes after creation.', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tests_app.test')),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='tests_app.examsession')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='exam_template',
            field=models.ForeignKey(blank=True, help_text='Set the first time this exam is rescheduled — groups this Test (and any later versions) under one stable exam identity so it can have multiple scheduled Exam Sessions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='tests_app.examtemplate'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Null for every attempt made before this feature existed, or made directly against a Test that has never been scheduled through a session — those keep ranking against test-wide attempts exactly as before.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='tests_app.examsession'),
        ),
    ]
