# Generated by Django 4.2.30 on 2026-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0009_test_version_number_alter_test_is_draft_examtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='university',
            field=models.CharField(blank=True, help_text='Conducting institution for Past Year Questions, e.g. IOM, MOE, BPKIHS, KU — the top-level grouping on the student Past Year Questions page (Year is the level below it).', max_length=100),
        ),
    ]
