# Generated by Django 4.2.30 on 2026-08-25 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_batch_enrollment_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_app', '0010_test_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_batches',
            field=models.ManyToManyField(blank=True, help_text='Specific course cohort(s) (e.g. "2082 Batch") granted access, independent of the broader courses assignment.', related_name='assigned_tests', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='test',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Individual students explicitly granted access regardless of course/batch assignment.', related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='needs_course_review',
            field=models.BooleanField(default=False, help_text='Set only by the one-time migration that introduced default-deny access control, for legacy exams that were published with no course assignment and could not be safely auto-mapped to exactly one course. While True, this exam keeps its pre-migration "visible to everyone" behavior so no existing access is silently revoked — an admin should assign real courses and clear this flag. Never set for exams created after this feature shipped.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Which subcourse(s) this exam is assigned to. Blank = visible to no one until assigned (see needs_course_review for the one-time legacy exception), NOT "visible to everyone" — that opt-out-by-omission default was the root cause of exams leaking across unrelated courses.', related_name='mapped_tests', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='On (the default for every new exam) = only visible to staff — an admin/teacher must explicitly assign courses/students/batches and publish before students can see it. Off = visible to eligible students per the courses/assigned_students/assigned_batches assignment below.'),
        ),
    ]
