# Generated by Django 4.2.30 on 2026-08-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0011_test_assigned_batches_test_assigned_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
