# Generated by Django 4.2.30 on 2026-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0014_savedexamview'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['exam_type', 'is_draft'], name='test_examtype_isdraft_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status', 'score'], name='ta_test_status_score_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', 'status'], name='ta_user_test_status_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status'], name='ta_user_status_idx'),
        ),
    ]
