# Generated by Django 4.2.30 on 2026-08-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0015_test_test_examtype_isdraft_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='stats_applied_at',
            field=models.DateTimeField(blank=True, help_text="Deadlock-fix audit: set when this attempt's cross-student Question/Option aggregate stat deltas (total_attempts, correct_attempts, pick_count, pick_percentage — NOT scoring/ranking/QuestionAttempt, which stay synchronous) have been applied by the async stats worker (see tests_app/stats_tasks.py). An atomic claim-before-apply/unclaim-on-failure guard against Cloud Tasks at-least-once redelivery double-counting or silently losing stats.", null=True),
        ),
    ]
