# Generated by Django 4.2.30 on 2026-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0016_testattempt_stats_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='stats_applied_at',
            field=models.DateTimeField(blank=True, help_text='Deadlock-fix audit: set when this attempt\'s cross-student Question/Option aggregate stat deltas (total_attempts, correct_attempts, pick_count, pick_percentage — NOT scoring/ranking/QuestionAttempt, which stay synchronous) have been applied by the async stats worker (see tests_app/stats_tasks.py). Written only inside the same transaction as the apply itself (a locked check-then-apply-then-mark), so it can only ever be non-NULL after the deltas actually landed — never as a claim taken before the work, which a crash mid-task could otherwise leave stuck "done" with the stats never applied. NULL is always safe to retry.', null=True),
        ),
    ]
