# Generated by Django 4.2.30 on 2026-09-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0017_alter_testattempt_stats_applied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTypePolicy',
            fields=[
                ('exam_type', models.CharField(choices=[('qbank', 'Question Bank'), ('daily', 'Daily Test'), ('mock', 'Mock Test'), ('grand', 'Grand Test'), ('pyq', 'Past Year Questions')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('default_questions_per_page', models.PositiveIntegerField(default=1)),
                ('default_negative_marking', models.BooleanField(default=True)),
                ('default_shuffle_questions', models.BooleanField(default=True)),
                ('default_shuffle_options', models.BooleanField(default=True)),
                ('default_max_attempts', models.PositiveIntegerField(default=1)),
                ('default_solutions_visibility', models.CharField(choices=[('auto', 'Automatically, once the exam window ends'), ('manual', 'Only when I click "Release solutions"')], default='auto', max_length=10)),
                ('default_is_draft', models.BooleanField(default=True, help_text="On (recommended) = new exams of this category start as drafts, invisible to students until an admin explicitly publishes them — matches Test.is_draft's own safe-by-default documentation.")),
                ('default_is_pro', models.BooleanField(default=False)),
                ('default_free_preview_questions', models.PositiveIntegerField(default=0)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam type policy',
                'verbose_name_plural': 'Exam type policies',
                'ordering': ['exam_type'],
            },
        ),
    ]
