# Generated by Django 4.2.30 on 2026-09-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0019_seed_examtypepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text="Phase 6: True when this attempt was finalized by the server because its effective deadline (MIN(start_time + test.duration_minutes, session.end_datetime)) passed, rather than by the student's own Submit action. Deliberately NOT a separate status value — an auto-submitted attempt is 'submitted' in every way that matters (scored, ranked, reviewable) — this is purely an informational marker so the UI can show 'time ran out' instead of 'you submitted this' (see tests_app/lifecycle.py's module docstring for the full reasoning)."),
        ),
    ]
