# Generated by Django 4.2.30 on 2026-09-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_importbatch_dedup_claimed_at_and_more'),
        ('tests_app', '0021_solutions_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text="This question's position in the test at finalization time.")),
                ('text', models.TextField()),
                ('image_data', models.JSONField(blank=True, help_text='Resolved {url, variants, width, height} — see media_library.serializers.resolve_image_data.', null=True)),
                ('latex', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_image_data', models.JSONField(blank=True, null=True)),
                ('explanation_latex', models.TextField(blank=True)),
                ('explanation_video_url', models.URLField(blank=True)),
                ('key_takeaway', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('reference_book_name', models.CharField(blank=True, max_length=255)),
                ('reference_edition', models.CharField(blank=True, max_length=50)),
                ('reference_chapter', models.CharField(blank=True, max_length=255)),
                ('reference_page', models.CharField(blank=True, max_length=50)),
                ('reference_url', models.URLField(blank=True)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('options_snapshot', models.JSONField(default=list)),
                ('selected_option_original_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_snapshots', to='tests_app.testattempt')),
                ('question', models.ForeignKey(blank=True, help_text='The live Question this was captured from, if it still exists — for admin/debugging traceability only. Every field actually used for display below is a duplicated, frozen copy, not derived from this FK, so it stays correct even if this goes null.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('attempt', 'order')},
            },
        ),
    ]
