# Generated by Django 4.2.30 on 2026-09-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_merge_20260906_0849'),
        ('tests_app', '0022_attempt_question_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False, help_text='Whether this row exists because the attempt was frozen in preview-only mode at start time. Informational/audit only — no access decision reads this field directly.')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='tests_app.testattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('attempt', 'order')},
            },
        ),
    ]
