# Generated by Django 4.2.30 on 2026-09-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0023_attemptquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='marks_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Question.marks at attempt-creation time. Null for a pre-GT3-1 attempt — _score_and_rank() then falls back to live Question.marks, exactly as it always has.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='negative_marks_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Question.negative_marks at attempt-creation time — see marks_snapshot.', max_digits=5, null=True),
        ),
    ]
