# Generated by Django 4.2.30 on 2026-09-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0024_attemptquestion_marks_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='review_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Grand Test 3.0 / GT3-4: how many days after the exam window closes the DETAILED per-question review (question/answer/solution list) stays available. Null (the default) = permanent — the exact, unchanged behavior every existing Test already has, since this field starts null for every row. The attempt/result OVERVIEW (score, rank, percentile, accuracy) never expires regardless of this setting — only the detailed question-by-question breakdown does. Lives here (not on ExamSession) to match solutions_visibility/solutions_released_at, which already live at this same Test level — a genuinely per-session override was not something any current Grand Test usage pattern required.', null=True),
        ),
    ]
