# Generated by Django 4.2.30 on 2026-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0025_test_review_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandTestMotivationBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.CharField(help_text='e.g. "Excellent Progress"', max_length=100)),
                ('message', models.TextField()),
                ('recommended_practice_hint', models.CharField(blank=True, help_text='Short, generic guidance, e.g. "Weak-topic practice + timed Mock Test" — never a specific exam name.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-min_percent'],
            },
        ),
    ]
