# Generated by Django 4.2.30 on 2026-08-29 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_backfill_enrollment_from_subscription'),
        ('tests_app', '0014_savedexamview'),
        ('academics', '0020_alter_questionevent_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPracticeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Platform-wide kill switch. Off = every endpoint returns feature-disabled.')),
                ('min_questions_per_session', models.PositiveIntegerField(default=5)),
                ('max_questions_per_session', models.PositiveIntegerField(default=20)),
                ('default_questions_per_session', models.PositiveIntegerField(default=10)),
                ('weak_topic_accuracy_max_pct', models.PositiveIntegerField(default=50, help_text="A topic's accuracy within the source test at/below this = weak, for Source Weak Areas mode. Deliberately separate from QuestionBankConfig/tests_app.performance thresholds — this one is source-scoped, those are platform-wide.")),
                ('min_mistakes_to_recommend', models.PositiveIntegerField(default=2, help_text='Fewer wrong/skipped answers than this on the source test and no Smart Practice CTA is shown at all.')),
                ('ai_coach_enabled', models.BooleanField(default=False, help_text='v2 — must stay False until a real explanation layer ships. No AI call exists yet.')),
            ],
            options={
                'verbose_name': 'Smart Practice settings',
                'verbose_name_plural': 'Smart Practice settings',
            },
        ),
        migrations.CreateModel(
            name='SmartPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('retry_mistakes', 'Retry Mistakes'), ('source_weak_areas', 'Source Weak Areas'), ('concept_reinforcement', 'Concept Reinforcement')], max_length=25)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=15)),
                ('question_count', models.PositiveIntegerField()),
                ('selection_reason', models.TextField(blank=True, help_text='Template-generated in v1, e.g. "5 questions you missed on Cardiac Physiology in this test."')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_practice_sessions', to='tests_app.testattempt')),
                ('source_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_practice_sessions', to='tests_app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartPracticeSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('source_mistake', 'Missed in source test'), ('source_weak_topic', 'Same weak topic, new question'), ('expansion_pool', 'Related concept')], max_length=20)),
                ('is_correct', models.BooleanField(blank=True, help_text='Null = not yet answered.', null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.option')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='smart_practice.smartpracticesession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='smartpracticesession',
            index=models.Index(fields=['user', 'source_test'], name='smart_pract_user_id_6bb52e_idx'),
        ),
        migrations.AddIndex(
            model_name='smartpracticesession',
            index=models.Index(fields=['user', 'status'], name='smart_pract_user_id_64df7b_idx'),
        ),
    ]
