# Generated by Django 4.2.30 on 2026-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartpracticesession',
            name='mode',
            field=models.CharField(choices=[('retry_mistakes', 'Master Mistakes'), ('source_weak_areas', 'Fix Weak Areas'), ('concept_reinforcement', 'Strengthen Concepts'), ('due_review', 'Due for Review'), ('new_questions', 'New Questions'), ('bookmarked', 'Bookmarked'), ('ai_mixed', 'AI Mixed Practice')], max_length=25),
        ),
        migrations.AlterField(
            model_name='smartpracticesessionquestion',
            name='origin',
            field=models.CharField(choices=[('source_mistake', 'Missed in source test'), ('source_weak_topic', 'Same weak topic, new question'), ('expansion_pool', 'Related concept'), ('due_review', 'Due for spaced review'), ('new_question', 'Never attempted before'), ('bookmarked', 'Bookmarked')], max_length=20),
        ),
    ]
