# Generated by Django 4.2.30 on 2026-09-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeStarterPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('qbank', 'Practice / QBank (questions)'), ('mock_test', 'Mock Test (attempts)'), ('daily_test', 'Daily Test (attempts)'), ('grand_test', 'Grand Test (attempts)'), ('pyq', 'Past Year Questions (questions)')], max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Free quota granted to every newly-provisioned student. Ignored if "unlimited" is set.')),
                ('unlimited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Off = no Free Starter entitlement of this resource_type is granted at registration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource_type'],
            },
        ),
        migrations.CreateModel(
            name='FreeStarterEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('qbank', 'Practice / QBank (questions)'), ('mock_test', 'Mock Test (attempts)'), ('daily_test', 'Daily Test (attempts)'), ('grand_test', 'Grand Test (attempts)'), ('pyq', 'Past Year Questions (questions)')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unlimited', models.BooleanField(default=False)),
                ('used', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Blank = does not expire on its own (only exhausts by usage).', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_starter_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='EntitlementEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(blank=True, max_length=30)),
                ('event', models.CharField(choices=[('created', 'Created'), ('consumed', 'Consumed'), ('exhausted', 'Exhausted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('restored', 'Restored')], max_length=15)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who/what caused this event — an admin for a manual action, blank for a system-triggered one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'resource_type'], name='entitlement_user_id_b10ebc_idx')],
            },
        ),
    ]
