# Generated by Django 4.2.30 on 2026-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freestarterpolicy',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days after provisioning this entitlement stays valid. Blank = does not expire on its own (only exhausts by usage). Phase 3 — never hardcoded, e.g. 7/14/30 are examples only.', null=True),
        ),
    ]
