# Generated by Django 4.2.30 on 2026-08-01 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_option_latex_question_explanation_latex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('prefix', models.CharField(help_text='Matches the "Course Prefix" column when importing questions from Excel.', max_length=20, unique=True)),
                ('program_group', models.CharField(blank=True, help_text='e.g. CEE-PG, CEE-UG, NHPC', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['program_group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Blank = lifetime access', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLiveExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('ioe_styled_ui', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('question_count', models.PositiveIntegerField(default=25)),
                ('negative_marking_percent', models.PositiveIntegerField(default=25)),
                ('auto_generate_daily', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_live_exam_config', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLiveExamShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('label', models.CharField(default='Shift 1', max_length=50)),
                ('start_time', models.TimeField()),
                ('is_generated', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='courses.dailyliveexamconfig')),
                ('questions', models.ManyToManyField(blank=True, related_name='daily_live_shifts', to='academics.question')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyPracticeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('target_total', models.PositiveIntegerField(default=10)),
                ('free_questions', models.PositiveIntegerField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_practice_config', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Blank = never expires', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('year_bs', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=180)),
                ('negative_marking_percent', models.PositiveIntegerField(default=0)),
                ('free_for_everyone', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='test_series_banners/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_series', to='courses.course')),
                ('questions', models.ManyToManyField(blank=True, related_name='test_series', to='academics.question')),
            ],
            options={
                'verbose_name_plural': 'Test series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTestExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('generate_new', 'Generate new (uses the saved Live Exam format)'), ('reuse_daily_live', 'Reuse an existing Daily Live Exam set'), ('reuse_mock', "Reuse another Mock Test's question set (by code)"), ('custom_upload', 'Custom Excel upload')], default='generate_new', max_length=20)),
                ('source_set_code', models.CharField(blank=True, max_length=20)),
                ('open_mode', models.CharField(choices=[('now', 'Start now'), ('scheduled', 'Scheduled')], default='now', max_length=10)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('solutions_visibility', models.CharField(choices=[('auto', 'Automatically, once the exam window ends'), ('manual', 'Only when I click "Release solutions"')], default='auto', max_length=10)),
                ('exam_name', models.CharField(blank=True, max_length=200)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mocktest_logos/')),
                ('is_public', models.BooleanField(default=False)),
                ('feature_on_homepage', models.BooleanField(default=False)),
                ('question_set_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_sets', to='courses.course')),
                ('questions', models.ManyToManyField(blank=True, related_name='mock_test_sets', to='academics.question')),
                ('source_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.dailyliveexamshift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='courses.course')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPracticeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_mark_count', models.PositiveIntegerField(default=0)),
                ('two_mark_count', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.chapter')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='courses.dailypracticeconfig')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('package', 'Package')], default='free', max_length=10)),
                ('student_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
