# Generated by Django 4.2.30 on 2026-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestexamset',
            name='access_window_hours',
            field=models.PositiveIntegerField(default=24, help_text='How long a guest resume code stays valid for.'),
        ),
        migrations.AddField(
            model_name='mocktestexamset',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testseries',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testseries',
            name='shuffle_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testseries',
            name='solutions_visibility',
            field=models.CharField(choices=[('auto', 'Automatically, once the exam window ends'), ('manual', 'Only when I click "Release solutions"')], default='auto', max_length=10),
        ),
    ]
