# Generated by Django 4.2.30 on 2026-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_mocktestexamset_access_window_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#0b5fd9', help_text='Accent color (hex) for the homepage course card.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the homepage course card.'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='📘', help_text='Emoji shown on the homepage course card.', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Off = hidden from the homepage "Choose your course" section.'),
        ),
    ]
