# Generated by Django 4.2.30 on 2026-08-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_color_course_description_course_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyliveexamshift',
            name='config',
        ),
        migrations.RemoveField(
            model_name='dailyliveexamshift',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='dailypracticeconfig',
            name='course',
        ),
        migrations.RemoveField(
            model_name='dailypracticerule',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='dailypracticerule',
            name='config',
        ),
        migrations.RemoveField(
            model_name='dailypracticerule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='mocktestexamset',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mocktestexamset',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='mocktestexamset',
            name='source_shift',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='course',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='questions',
        ),
        migrations.DeleteModel(
            name='DailyLiveExamConfig',
        ),
        migrations.DeleteModel(
            name='DailyLiveExamShift',
        ),
        migrations.DeleteModel(
            name='DailyPracticeConfig',
        ),
        migrations.DeleteModel(
            name='DailyPracticeRule',
        ),
        migrations.DeleteModel(
            name='MockTestExamSet',
        ),
        migrations.DeleteModel(
            name='TestSeries',
        ),
    ]
