# Generated by Django 4.2.30 on 2026-08-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_legacy_exam_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
