# Generated by Django 4.2.30 on 2026-08-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_vestigial_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "2082 Batch"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Which intake/cohort of this course the student belongs to — used for batch-scoped exam assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.batch'),
        ),
    ]
