"""
Django settings for hamromentor project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-rgrqwz+--!+)697p+lbpm9-20s+u3hszsq3s*e^9tw4a!zz)m$',
)

# Shared secret for the external cron endpoints under /api/cron/*.
CRON_SECRET = os.environ.get('CRON_SECRET', 'dev-cron-secret-change-me')

# Referral program — applied automatically on a referred student's first approved purchase.
REFERRAL_FRIEND_DISCOUNT_PERCENT = int(os.environ.get('REFERRAL_FRIEND_DISCOUNT_PERCENT', 10))
REFERRAL_REWARD_AMOUNT = int(os.environ.get('REFERRAL_REWARD_AMOUNT', 100))

# Email — defaults to printing to the console in dev. Set EMAIL_HOST/EMAIL_HOST_USER/
# EMAIL_HOST_PASSWORD (and switch EMAIL_BACKEND to smtp) once real SMTP creds exist.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Dr. Gutka <no-reply@hamromentor.com>')

# Student-facing Frontend base URL — used to build links inside outbound emails
# (e.g. "view your invoice"). Not the API URL.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# media_library — image upload/optimization/storage (see media_library app).
# All blank/False in local dev, where MediaUploadView isn't expected to be
# exercised; production (Cloud Run) sets every one of these via env vars.
GCP_PROJECT_ID = os.environ.get('GCP_PROJECT_ID', '')
GCP_REGION = os.environ.get('GCP_REGION', 'us-central1')
MEDIA_GCS_PRIVATE_BUCKET = os.environ.get('MEDIA_GCS_PRIVATE_BUCKET', '')
MEDIA_GCS_PUBLIC_BUCKET = os.environ.get('MEDIA_GCS_PUBLIC_BUCKET', '')
CLOUD_TASKS_QUEUE = os.environ.get('CLOUD_TASKS_QUEUE', 'image-processing')
# The Backend's own public URL — Cloud Tasks calls back into this service's
# /api/media/process/ endpoint.
BACKEND_INTERNAL_URL = os.environ.get('BACKEND_INTERNAL_URL', 'http://localhost:8000')
# Shared-secret auth for the Cloud Tasks handler, matching this project's
# existing X-Cron-Secret convention (see courses/views.py, billing/views.py).
MEDIA_PROCESSING_SECRET = os.environ.get('MEDIA_PROCESSING_SECRET', 'dev-media-secret-change-me')
# False in local dev (no Cloud Tasks queue to enqueue to) — processes
# inline/synchronously instead. True in production.
IMAGE_PROCESSING_ASYNC = os.environ.get('IMAGE_PROCESSING_ASYNC', 'False') == 'True'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

# Cloud Run terminates TLS at its own load balancer and forwards requests to
# this container over plain HTTP, setting X-Forwarded-Proto to indicate the
# original scheme. Without this, request.is_secure() is always False here,
# so every absolute URL Django builds (request.build_absolute_uri(), and
# every ImageField/FileField serialized through a DRF serializer with
# request context — e.g. PaymentMethod.qr_code_image, Question.explanation_image,
# Video.play_url) comes out as http://, which browsers block as mixed
# content on the https:// frontend — the exact cause of the payment QR
# code not rendering.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'academics',
    'tests_app',
    'videos_app',
    'core',
    'courses',
    'billing',
    'marketplace',
    'media_library',
    'smart_practice',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}

ROOT_URLCONF = 'hamromentor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hamromentor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('DB_NAME'):
    # Production (cPanel MySQL) — set via the Python App's Environment
    # Variables. Falls back to SQLite below when these aren't set, so local
    # dev is unaffected.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
            # Persist connections across requests instead of opening a new
            # one every time (scalability audit finding C3) — 60s is
            # deliberately short, not a long-lived pool: Cloud Run can
            # freeze/recycle an idle instance at any time, so a connection
            # kept alive too long risks being reused after it's gone stale
            # ("MySQL server has gone away"). CONN_HEALTH_CHECKS pings a
            # reused connection before Django trusts it, which is exactly
            # the safety net a short-lived serverless container needs —
            # a dead connection is discarded and reopened instead of
            # surfacing as a 500 to the student mid-request. Both are
            # env-overridable so this can be tuned from load-test results
            # without a code change.
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache (scalability audit finding: no shared cache existed anywhere in the
# app, so even DRF's own throttle counters were per-process and effectively
# unenforced across gunicorn workers/Cloud Run instances). This is Phase 0
# infrastructure only — wiring the backend so it exists and is safe to use.
# No view/service code reads or writes through it yet; that's deliberately
# separate, later work (locked_subject_ids, the performance dashboard, etc.
# each need their own considered cache key + invalidation + TTL, not a
# blanket "cache everything" flip). Falls back to Django's default
# LocMemCache in local dev (no REDIS_HOST set) exactly like DATABASES
# above falls back to sqlite — nothing here requires Redis to run locally.
#
# IGNORE_EXCEPTIONS + a null CLIENT_CLASS log handler mean a Redis outage
# degrades every cache read to a miss (silently falls through to the real
# DB/computation) instead of turning into a 500 for students — a cache is
# an optimization, not a dependency the app should go down without.
if os.environ.get('REDIS_HOST'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{os.environ['REDIS_HOST']}:{os.environ.get('REDIS_PORT', '6379')}/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
                'SOCKET_CONNECT_TIMEOUT': 2,
                'SOCKET_TIMEOUT': 2,
            },
        }
    }
    DJANGO_REDIS_IGNORE_EXCEPTIONS = True
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloud Run's local disk is ephemeral — wiped on every new revision deploy,
# container restart, or when traffic scales to a different instance — so a
# plain ImageField/FileField saved with Django's default FileSystemStorage
# (payment QR codes, payment screenshots, banners, thumbnails, profile
# photos — anything not already routed through media_library's MediaAsset
# pipeline) can silently 404 for users within hours of being uploaded. Falls
# back to local storage when MEDIA_GCS_PUBLIC_BUCKET isn't configured
# (local dev/tests), matching every other MEDIA_GCS_* setting's "blank in
# local dev" convention above.
if MEDIA_GCS_PUBLIC_BUCKET:
    DEFAULT_FILE_STORAGE = 'media_library.django_storage.PublicGCSStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
