# Generated by Django 4.2.30 on 2026-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='latex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_latex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='latex',
            field=models.TextField(blank=True, help_text='Optional LaTeX, e.g. \\int_0^1 x^2\\,dx'),
        ),
        migrations.AddField(
            model_name='question',
            name='past_exam_years',
            field=models.CharField(blank=True, help_text='Comma-separated BS years this question appeared in, e.g. "2078,2080"', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='prefix',
            field=models.CharField(blank=True, help_text='Short code (e.g. PHY, BOT) matched against the "Subject Prefix" column when importing from Excel.', max_length=20),
        ),
    ]
