# Generated by Django 4.2.30 on 2026-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('academics', '0005_option_latex_question_explanation_latex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Which course(s) this question belongs to (a question can be shared across courses).', related_name='questions', to='courses.course'),
        ),
    ]
