# Generated by Django 4.2.30 on 2026-08-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_color_course_description_course_icon_and_more'),
        ('academics', '0006_question_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Which course(s) use this subject (a subject can be shared across courses, e.g. Physiology under both CEE-PG and NMCLE).', related_name='subjects', to='courses.course'),
        ),
    ]
