# Generated by Django 4.2.30 on 2026-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_free',
            field=models.BooleanField(default=True, help_text='On = anyone can practice this subject. Off = requires an active Question Bank subscription for one of its courses.'),
        ),
    ]
