# Generated by Django 4.2.30 on 2026-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='Book citations, paper links, or YouTube links backing the explanation — each entry is {type: book|paper|video|link, label, url}.'),
        ),
    ]
