# Generated by Django 4.2.30 on 2026-08-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_vestigial_promo_code'),
        ('academics', '0011_importbatch_importrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.chapter'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text="Which course(s) this batch's questions belong to — a file can cover multiple courses at once.", related_name='+', to='courses.course'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.topic'),
        ),
    ]
