# Generated by Django 4.2.30 on 2026-08-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_test_is_draft'),
        ('academics', '0012_importbatch_chapter_importbatch_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='created_test',
            field=models.ForeignKey(blank=True, help_text='Set once Import & Create Test successfully builds a Test from this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.test'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='import_mode',
            field=models.CharField(choices=[('question_bank', 'Import to Question Bank'), ('create_test', 'Import & Create Test')], default='question_bank', max_length=15),
        ),
    ]
