# Generated by Django 4.2.30 on 2026-08-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('academics', '0014_question_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Optimized/responsive replacement for `image`. See Question.image_asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_image_asset',
            field=models.ForeignKey(blank=True, help_text='Optimized/responsive replacement for `explanation_image`. See `image_asset`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Optimized/responsive replacement for `image`, via media_library. Falls back to `image` when unset — existing questions are unaffected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
    ]
