# Generated by Django 4.2.30 on 2026-08-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0015_option_image_asset_question_explanation_image_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_attempts_for_difficulty', models.PositiveIntegerField(default=30, help_text='A question needs at least this many attempts before actual_difficulty is computed. Below this, actual_difficulty stays blank.')),
                ('easy_min_pct', models.PositiveIntegerField(default=75, help_text='% correct at or above this = Easy.')),
                ('medium_min_pct', models.PositiveIntegerField(default=55, help_text='% correct at or above this (and below Easy) = Medium.')),
                ('hard_min_pct', models.PositiveIntegerField(default=30, help_text='% correct at or above this (and below Medium) = Hard. Below this = Very Hard.')),
                ('mastered_min_pct', models.PositiveIntegerField(default=80, help_text="Student's own accuracy on a question at/above this (with >=2 attempts) = Mastered.")),
                ('weak_max_pct', models.PositiveIntegerField(default=40, help_text="Student's own accuracy on a question at/below this = Weak.")),
                ('revision_interval_correct_days', models.PositiveIntegerField(default=7)),
                ('revision_interval_incorrect_days', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Question Bank settings',
                'verbose_name_plural': 'Question Bank settings',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('source', models.CharField(choices=[('qbank', 'QBank Practice'), ('test', 'Test')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='actual_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], help_text='Computed from real student performance by the recompute_question_difficulty command. Never set by hand, never overwrites instructor_difficulty.', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='actual_difficulty_sample_size',
            field=models.PositiveIntegerField(default=0, help_text='How many attempts actual_difficulty was computed from.'),
        ),
        migrations.AddField(
            model_name='question',
            name='actual_difficulty_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='instructor_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], help_text="Admin/teacher's own judgment call — independent of actual_difficulty below.", max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('conceptual', 'Conceptual'), ('recall', 'Recall'), ('clinical', 'Clinical'), ('numerical', 'Numerical'), ('image_based', 'Image-based'), ('other', 'Other')], max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Free-text keyword tags for search, e.g. ["vector", "scalar"].'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='incorrect_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='last_result',
            field=models.BooleanField(blank=True, help_text='Mirrors is_correct — kept as an explicit, nullable field for New (never attempted, still attempts_count=0) vs Incorrect.', null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='mastery_status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('need_practice', 'Need Practice'), ('weak', 'Weak'), ('mastered', 'Mastered')], default='new', max_length=15),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='revision_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'mastery_status'], name='academics_q_user_id_3bcdac_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'revision_due_at'], name='academics_q_user_id_f794f3_idx'),
        ),
        migrations.AddField(
            model_name='questionevent',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academics.question'),
        ),
        migrations.AddField(
            model_name='questionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questionevent',
            index=models.Index(fields=['user', 'question', 'created_at'], name='academics_q_user_id_95d4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='questionevent',
            index=models.Index(fields=['user', 'is_correct', 'created_at'], name='academics_q_user_id_4ebc34_idx'),
        ),
    ]
