# Generated by Django 4.2.30 on 2026-08-23 11:35

from django.conf import settings
from django.db import migrations


def merge_duplicate_attempts(apps, schema_editor):
    """Pre-existing rows were written via update_or_create with no DB-level
    uniqueness guarantee, so a rare concurrent-request race could in theory
    have created more than one QuestionAttempt per (user, question). Keep
    the most-recently-answered row (its is_correct/is_bookmarked reflect
    the latest real state), fold any bookmark=True from a duplicate into
    the survivor so a bookmark is never silently lost, then delete the
    rest. No-op if no duplicates exist. Must run before the unique
    constraint below, or that constraint would fail to apply on any
    environment where a duplicate happens to exist."""
    QuestionAttempt = apps.get_model('academics', 'QuestionAttempt')
    from django.db.models import Count

    dupes = (
        QuestionAttempt.objects.values('user_id', 'question_id')
        .annotate(n=Count('id')).filter(n__gt=1)
    )
    for row in dupes:
        rows = list(
            QuestionAttempt.objects.filter(user_id=row['user_id'], question_id=row['question_id'])
            .order_by('-answered_at', '-id')
        )
        survivor, extras = rows[0], rows[1:]
        if any(r.is_bookmarked for r in extras) and not survivor.is_bookmarked:
            survivor.is_bookmarked = True
            survivor.save(update_fields=['is_bookmarked'])
        QuestionAttempt.objects.filter(id__in=[r.id for r in extras]).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0016_questionbankconfig_questionevent_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_attempts, noop_reverse),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('user', 'question')},
        ),
    ]
