# Generated by Django 4.2.30 on 2026-08-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_medium_min_pct(apps, schema_editor):
    # AlterField's new default (50, down from 55) only applies to rows
    # created from here on — an already-saved QuestionBankConfig singleton
    # (pk=1) keeps its old value unless explicitly updated here, so the new
    # 90/75/50/30 difficulty thresholds take effect immediately.
    QuestionBankConfig = apps.get_model('academics', 'QuestionBankConfig')
    QuestionBankConfig.objects.filter(pk=1, medium_min_pct=55).update(medium_min_pct=50)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0017_alter_questionattempt_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='explanation',
            field=models.TextField(blank=True, help_text='Why this option is right/wrong — shown per-option after submission.'),
        ),
        migrations.AddField(
            model_name='option',
            name='pick_count',
            field=models.PositiveIntegerField(default=0, help_text='Distinct students currently selecting this option.'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Of total_attempts, how many are currently correct.'),
        ),
        migrations.AddField(
            model_name='question',
            name='key_takeaway',
            field=models.TextField(blank=True, help_text='One high-yield exam point shown after the explanation.'),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_chapter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_page',
            field=models.CharField(blank=True, help_text='e.g. "245" or "245-247".', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Distinct students with a current answer recorded. Not per-attempt.'),
        ),
        migrations.AddField(
            model_name='questionbankconfig',
            name='min_attempts_for_option_stats',
            field=models.PositiveIntegerField(default=5, help_text='A question needs at least this many recorded students before option percentages / "X% got this right" are shown. Below this, a privacy-safe message is shown instead.'),
        ),
        migrations.AddField(
            model_name='questionbankconfig',
            name='very_easy_min_pct',
            field=models.PositiveIntegerField(default=90, help_text='% correct at or above this = Very Easy.'),
        ),
        migrations.AddField(
            model_name='questionevent',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='actual_difficulty',
            field=models.CharField(blank=True, choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Moderate'), ('hard', 'Difficult'), ('very_hard', 'Very Difficult')], help_text='Computed from real student performance by the recompute_question_difficulty command. Never set by hand, never overwrites instructor_difficulty.', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='instructor_difficulty',
            field=models.CharField(blank=True, choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Moderate'), ('hard', 'Difficult'), ('very_hard', 'Very Difficult')], help_text="Admin/teacher's own judgment call — independent of actual_difficulty below.", max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='Book citations, paper links, or YouTube links backing the explanation — each entry is {type: book|paper|video|link, label, url}. Supplementary only — see reference_book below for the single structured primary citation.'),
        ),
        migrations.AlterField(
            model_name='questionbankconfig',
            name='easy_min_pct',
            field=models.PositiveIntegerField(default=75, help_text='% correct at or above this (and below Very Easy) = Easy.'),
        ),
        migrations.AlterField(
            model_name='questionbankconfig',
            name='hard_min_pct',
            field=models.PositiveIntegerField(default=30, help_text='% correct at or above this (and below Moderate) = Difficult. Below this = Very Difficult.'),
        ),
        migrations.AlterField(
            model_name='questionbankconfig',
            name='medium_min_pct',
            field=models.PositiveIntegerField(default=50, help_text='% correct at or above this (and below Easy) = Moderate.'),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_book',
            field=models.ForeignKey(blank=True, help_text='Primary structured citation for this question — rendered in its own Reference card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='academics.referencebook'),
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('incorrect_answer', 'Incorrect answer'), ('incorrect_explanation', 'Incorrect explanation'), ('ambiguous', 'Ambiguous question'), ('typo', 'Typographical error'), ('outdated', 'Outdated information'), ('poor_image', 'Poor image'), ('other', 'Other')], max_length=25)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='academics.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='academics_q_status_dadb8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionDifficultyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_ratings', to='academics.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
        migrations.RunPython(backfill_medium_min_pct, migrations.RunPython.noop),
    ]
