# Generated by Django 4.2.30 on 2026-08-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_referencebook_option_explanation_option_pick_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='confidence',
            field=models.CharField(blank=True, choices=[('guess', 'Guess'), ('unsure', 'Unsure'), ('confident', 'Confident')], help_text='How sure the student felt about their latest answer, self-reported in QBank practice only (never asked in Test Mode). Used to surface "confident but incorrect" as a likely misconception.', max_length=10),
        ),
    ]
