# Generated by Django 4.2.30 on 2026-08-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_questionattempt_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionevent',
            name='source',
            field=models.CharField(choices=[('qbank', 'QBank Practice'), ('test', 'Test'), ('smart', 'Smart Practice')], max_length=10),
        ),
    ]
