# Generated by Django 4.2.30 on 2026-08-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_questionevent_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPublicIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
