# Generated by Django 4.2.30 on 2026-08-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_seed_question_public_id_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='processing_claimed_at',
            field=models.DateTimeField(blank=True, help_text='Scalability audit Phase 2.2: set atomically when a background import run (Cloud Task or its synchronous fallback) claims this batch, so a duplicate/retried task delivery for the same batch (Cloud Tasks is at-least-once, not exactly-once) sees it is already being processed and exits instead of double-importing rows. A claim older than IMPORT_CLAIM_STALE_MINUTES is treated as abandoned (the instance that held it likely died) and can be reclaimed by a retry.', null=True),
        ),
    ]
