# Generated by Django 4.2.30 on 2026-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_question_text_fulltext_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='dedup_claimed_at',
            field=models.DateTimeField(blank=True, help_text='Same staleness-reclaim pattern as processing_claimed_at, but for the dedup worker specifically — kept as its own field since dedup and import are independent operations that can each get stuck on their own schedule. A claim older than DEDUP_CLAIM_STALE_MINUTES is reclaimable.', null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dedup_completed_at',
            field=models.DateTimeField(blank=True, help_text='When dedup_status last became "completed" — observability only.', null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dedup_generation',
            field=models.PositiveIntegerField(default=0, help_text="Incremented every time the taxonomy PATCH changes Subject to a genuinely different value (never on Chapter/Topic/course changes, and never on re-selecting the same Subject — see ImportBatchTaxonomyView.patch()). The version token a stale, superseded dedup worker checks against before writing any row result, so a slow run for an old Subject can never overwrite a newer Subject's results. The Cloud Task name is generation-scoped (dedup-batch-{id}-gen-{generation}) so Cloud Tasks itself also never conflates two different generations under one task identity."),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dedup_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], help_text='Bulk-import taxonomy audit (Phase 3): async duplicate-detection status for the CURRENT dedup_generation. Blank until a Subject is first selected. A separate field from ImportBatch.status on purpose — dedup can run many times while status stays "ready", and reusing status would make its own well-established meaning ambiguous.', max_length=15),
        ),
    ]
