# Generated by Django 4.2.30 on 2026-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_importbatch_dedup_claimed_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'chapter', 'topic'], name='question_taxonomy_idx'),
        ),
    ]
