# Generated by Django 4.2.30 on 2026-09-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_question_question_taxonomy_idx'),
        ('academics', '0027_importbatch_dedup_compat_defaults'),
    ]

    operations = [
    ]
