# Generated by Django 4.2.30 on 2026-09-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_merge_20260906_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='error_skipped',
            field=models.BooleanField(default=False, help_text='Bulk-import Preview & Validate audit: an explicit admin decision to bypass this Error row for the current import, without touching its `status` (stays "error") or deleting it — the row keeps showing its real validation errors and can still be edited/fixed, but no longer counts toward blocking the batch, and the UI shows it as "Skipped" with an Undo option. Deliberately a separate field rather than overloading `status`, which already has its own "skipped" value meaning something different (a duplicate row skipped at IMPORT time, set by run_import() — see ImportRow.STATUS_CHOICES/import_engine.run_import) — collapsing the two would make an error-skipped row indistinguishable from an imported-and-skipped-duplicate row, and would wrongly exclude it from run_import\'s error exclusion query the moment status changed.'),
        ),
    ]
