# Generated by Django 4.2.30 on 2026-09-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0027_seed_grandtestmotivationband'),
        ('academics', '0029_importrow_error_skipped'),
        ('videos_app', '0002_video_lms_rewrite'),
        ('billing', '0016_alter_grandtestaccess_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_backfill_enrollment_from_registered_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('EMAIL_VERIFIED', 'Email Verified'), ('PASSWORD_CHANGED', 'Password Changed'), ('LOGIN_SECURITY_ALERT', 'Login Security Alert'), ('COURSE_ENROLLED', 'Course Enrolled'), ('COURSE_ACCESS_EXPIRING', 'Course Access Expiring'), ('COURSE_ACCESS_EXPIRED', 'Course Access Expired'), ('PURCHASE_CREATED', 'Purchase Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('PAYMENT_FAILED', 'Payment Failed'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('DAILY_TEST_PUBLISHED', 'Daily Test Published'), ('DAILY_TEST_AVAILABLE', 'Daily Test Available'), ('DAILY_TEST_ENDING', 'Daily Test Ending'), ('DAILY_TEST_CLOSED', 'Daily Test Closed'), ('DAILY_TEST_RESULT_AVAILABLE', 'Daily Test Result Available'), ('MOCK_TEST_AVAILABLE', 'Mock Test Available'), ('MOCK_TEST_RESULT_AVAILABLE', 'Mock Test Result Available'), ('GRAND_TEST_SCHEDULED', 'Grand Test Scheduled'), ('GRAND_TEST_REMINDER', 'Grand Test Reminder'), ('GRAND_TEST_STARTING', 'Grand Test Starting'), ('GRAND_TEST_LIVE', 'Grand Test Live'), ('GRAND_TEST_ENDING', 'Grand Test Ending'), ('GRAND_TEST_CLOSED', 'Grand Test Closed'), ('GRAND_TEST_RESULT_AVAILABLE', 'Grand Test Result Available'), ('GRAND_TEST_RANK_AVAILABLE', 'Grand Test Rank Available'), ('NEW_QUESTIONS_AVAILABLE', 'New Questions Available'), ('SMART_PRACTICE_READY', 'Smart Practice Ready'), ('REVISION_DUE', 'Revision Due'), ('WEAK_TOPIC_DETECTED', 'Weak Topic Detected'), ('LEARNING_STREAK', 'Learning Streak'), ('NEW_VIDEO_AVAILABLE', 'New Video Available'), ('NEW_CHAPTER_AVAILABLE', 'New Chapter Available'), ('ANNOUNCEMENT', 'Announcement'), ('MAINTENANCE', 'Maintenance'), ('IMPORTANT_SYSTEM_ALERT', 'Important System Alert')], max_length=40)),
                ('category', models.CharField(choices=[('tests', 'Tests'), ('results', 'Results'), ('learning', 'Learning'), ('courses', 'Courses'), ('billing', 'Billing'), ('announcements', 'Announcements'), ('marketing', 'Marketing'), ('security', 'Security')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, help_text='Structured deep-link path the frontend navigates to on click — never reconstructed from title/body text (architecture prompt §16).', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='dispatched', max_length=15)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('event_id', models.CharField(blank=True, help_text='Correlates this row back to the domain event that raised it, for observability (architecture prompt §41) — not a uniqueness constraint itself.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='NULL = deliver immediately. A future time holds this in STATUS_SCHEDULED until a dispatch sweep (services.dispatch_due_notifications) picks it up.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Past this time the notification is stale (e.g. a Grand Test reminder for a test that already started) — a future UI/eligibility layer may choose to stop surfacing it as new; this field alone does not delete or hide anything.', null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.testattempt')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.course')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.purchase')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.question')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos_app.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tests', 'Tests'), ('results', 'Results'), ('learning', 'Learning'), ('courses', 'Courses'), ('billing', 'Billing'), ('announcements', 'Announcements'), ('marketing', 'Marketing'), ('security', 'Security')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('push', 'Web Push'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'channel', 'course')},
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('push', 'Web Push'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('skipped', 'Skipped')], default='queued', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'channel')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_554261_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'course', '-created_at'], name='notificatio_user_id_4dfbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_d8d933_idx'),
        ),
    ]
