# Generated by Django 4.2.30 on 2026-08-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0014_question_seo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=10)),
                ('image_type', models.CharField(choices=[('student_avatar', 'Student Avatar'), ('teacher_avatar', 'Teacher Avatar'), ('course_thumbnail', 'Course Thumbnail'), ('question_image', 'Question Image'), ('option_image', 'Option Image'), ('explanation_image', 'Explanation Image'), ('banner', 'Banner'), ('logo', 'Logo'), ('rich_text', 'Rich Text Inline'), ('other', 'Other')], max_length=32)),
                ('category', models.CharField(choices=[('diagram', 'Diagram'), ('photograph', 'Photograph'), ('xray', 'X-ray'), ('ct_mri', 'CT/MRI'), ('histology', 'Histology'), ('ecg', 'ECG'), ('screenshot_table', 'Screenshot/Table'), ('other', 'Other')], default='other', max_length=20)),
                ('storage_key', models.CharField(max_length=512)),
                ('bucket', models.CharField(blank=True, help_text='Which GCS bucket the original lives in.', max_length=100)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=12)),
                ('processing_error', models.TextField(blank=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='academics.option')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='academics.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_hash'], name='media_libra_content_a746bd_idx'), models.Index(fields=['processing_status'], name='media_libra_process_a299c0_idx'), models.Index(fields=['image_type'], name='media_libra_image_t_68e3a4_idx')],
            },
        ),
    ]
